#!/usr/bin/env node

/**
 * FormFlare Interactive Setup Wizard & Manifest Summary
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const askQuestion = (query) =>
  new Promise((resolve) => rl.question(query, resolve));

async function main() {
  console.log(`
┌─────────────────────────────────────────────────────────────┐
│ 🔥 FormFlare Interactive Setup Wizard                       │
└─────────────────────────────────────────────────────────────┘
`);

  console.log('Select Setup Mode:');
  console.log('  1. 🛠️  Local Development Setup      [RECOMMENDED FOR LOCAL DEV]');
  console.log('  2. 🚀 Production Deployment Setup     [REQUIRED FOR PROD DEPLOY]');
  console.log('  3. ⚙️  Advanced Developer Tools     [OPTIONAL]');
  console.log('');

  const choice = (await askQuestion('Enter choice (1-3) [default: 1]: ')).trim() || '1';

  if (choice === '1') {
    await setupLocalDev();
  } else if (choice === '2') {
    await setupProdDeployment();
  } else if (choice === '3') {
    await setupAdvancedMenu();
  } else {
    console.log('Invalid choice. Exiting.');
  }

  rl.close();
}

async function setupLocalDev() {
  console.log('\n--- 🛠️  Local Development Environment Setup (.dev.vars) ---');
  console.log('This sets up your git-ignored local environment file (.dev.vars) for offline development.\n');

  const storageEngine = (await askQuestion('Select Storage Engine (kv/d1/none) [kv]: ')).trim().toLowerCase() || 'kv';
  const provider = (await askQuestion('Select Email Provider (console/none/resend/mailgun/sendgrid/mailtrap) [console]: ')).trim() || 'console';
  const emailTo = (await askQuestion('Enter notification target email (EMAIL_TO) [dev@example.com]: ')).trim() || 'dev@example.com';
  const emailFrom = (await askQuestion('Enter sender email (EMAIL_FROM) [noreply@localhost]: ')).trim() || 'noreply@localhost';
  const apiKey = (await askQuestion('Enter local API Key [dev-secret-key-123]: ')).trim() || 'dev-secret-key-123';

  const devVarsContent = `# FormFlare Local Development Environment (.dev.vars)
# Generated by FormFlare Interactive Setup Wizard
ENVIRONMENT=development
DEV_MODE=true
DEV_MOCK_TURNSTILE=true
ALLOWED_ORIGINS=*
STORAGE_ENGINE=${storageEngine}

TURNSTILE_SECRET_KEY=1x00000000000000000000AA00000000000
EMAIL_PROVIDER=${provider}
EMAIL_FROM=${emailFrom}
EMAIL_TO=${emailTo}
API_KEY=${apiKey}
`;

  const targetPath = path.join(__dirname, '..', '.dev.vars');
  fs.writeFileSync(targetPath, devVarsContent, 'utf-8');

  printManifest({
    modifiedFiles: [
      {
        path: targetPath,
        relativePath: '.dev.vars',
        status: 'CREATED / UPDATED',
        summary: `STORAGE_ENGINE=${storageEngine}, EMAIL_PROVIDER=${provider}, EMAIL_TO=${emailTo}, API_KEY=${apiKey}`,
      },
    ],
    nextSteps: [
      'Run local dev server: npx wrangler dev',
      'Submit a form locally to test form ingestion.',
      'Check status: git status (verify .dev.vars remains untracked)',
    ],
  });
}

async function setupProdDeployment() {
  console.log('\n--- 🚀 Production Deployment Setup (wrangler.overrides.toml) ---');
  console.log('Configures production environment variables & generates Wrangler infrastructure bindings.\n');

  const allowedOrigins = (await askQuestion('Enter allowed CORS origins (ALLOWED_ORIGINS) [e.g. https://brainendeavor.com,https://splitphase.io]: ')).trim() || '*';
  const storageEngine = (await askQuestion('Select Storage Engine: 1) Cloudflare KV [Default], 2) Cloudflare D1 SQL, 3) None [1]: ')).trim() || '1';

  let storageType = 'kv';
  let bindingBlock = '';

  if (storageEngine === '2' || storageEngine.toLowerCase() === 'd1') {
    storageType = 'd1';
    console.log('\n📌 Setting up Cloudflare D1 SQL Database:');
    console.log('1. If not yet created, run: npx wrangler d1 create formflare-db');
    console.log('2. Apply schema: npx wrangler d1 execute formflare-db --remote --file=./schema.sql\n');
    const dbId = (await askQuestion('Enter D1 Database ID (UUID): ')).trim();
    if (dbId) {
      bindingBlock = `
[[d1_databases]]
binding = "DB"
database_name = "formflare-db"
database_id = "${dbId}"
`;
    }
  } else if (storageEngine === '3' || storageEngine.toLowerCase() === 'none') {
    storageType = 'none';
  } else {
    storageType = 'kv';
    console.log('\n📌 Setting up Cloudflare Workers KV Namespace:');
    console.log('1. If not yet created, run: npx wrangler kv namespace create KV\n');
    const kvId = (await askQuestion('Enter KV Namespace ID: ')).trim();
    if (kvId) {
      bindingBlock = `
[[kv_namespaces]]
binding = "KV"
id = "${kvId}"
`;
    }
  }

  const provider = (await askQuestion('\nSelect Production Email Provider (mailtrap/resend/sendgrid/mailgun/none) [mailtrap]: ')).trim() || 'mailtrap';
  let emailTo = '';
  let emailFrom = '';

  if (provider !== 'none') {
    emailTo = (await askQuestion('Enter production alert recipient (EMAIL_TO) [e.g. alerts@yourdomain.com]: ')).trim();
    emailFrom = (await askQuestion('Enter production sender address (EMAIL_FROM) [e.g. contact@yourdomain.com]: ')).trim();
  }

  const overridesPath = path.join(__dirname, '..', 'wrangler.overrides.toml');
  const overridesContent = `# wrangler.overrides.toml (Git-Ignored Production Deployment Overrides)
# Generated by FormFlare Interactive Setup Wizard
name = "formflare"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[assets]
directory = "public"
binding = "ASSETS"

[[rules]]
type = "Text"
globs = ["**/*.mustache"]
fallthrough = true

[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "${allowedOrigins}"
STORAGE_ENGINE = "${storageType}"
RATE_LIMIT_ENABLED = "false"
RATE_LIMIT_REQUESTS = "10"
RATE_LIMIT_WINDOW = "60"
EMAIL_PROVIDER = "${provider}"
${emailTo ? `EMAIL_TO = "${emailTo}"` : ''}
${emailFrom ? `EMAIL_FROM = "${emailFrom}"` : ''}
${bindingBlock}
`;

  fs.writeFileSync(overridesPath, overridesContent, 'utf-8');

  console.log('\n📌 Cloudflare KMS Production Secret Commands');
  console.log('Execute the following commands in your terminal to set production secrets in Cloudflare KMS:\n');
  console.log('  npx wrangler secret put TURNSTILE_SECRET_KEY');
  console.log('  npx wrangler secret put API_KEY');
  if (provider !== 'none' && provider !== 'console') {
    console.log('  npx wrangler secret put EMAIL_API_KEY');
  }

  printManifest({
    modifiedFiles: [
      {
        path: overridesPath,
        relativePath: 'wrangler.overrides.toml',
        status: 'CREATED / UPDATED',
        summary: `STORAGE_ENGINE=${storageType}, EMAIL_PROVIDER=${provider}, ALLOWED_ORIGINS=${allowedOrigins}`,
      },
    ],
    nextSteps: [
      'Set Cloudflare KMS secrets listed above.',
      'Deploy to Cloudflare Workers: npm run deploy:prod',
    ],
  });
}

async function setupAdvancedMenu() {
  console.log('\n--- ⚙️  Advanced Developer Tools (Optional) ---');
  console.log('  1. Custom Domain Route & Production Overrides (wrangler.overrides.toml)');
  console.log('  2. Multi-Tenant Per-Site Secrets & Webhooks Helper');
  console.log('');

  const choice = (await askQuestion('Enter choice (1-2) [default: 1]: ')).trim() || '1';

  if (choice === '1') {
    await setupLocalRoute();
  } else if (choice === '2') {
    await setupMultiSiteSecrets();
  } else {
    console.log('Invalid choice.');
  }
}

async function setupLocalRoute() {
  console.log('\n--- 🌐 Custom Domain Route Setup (wrangler.overrides.toml) [OPTIONAL] ---');
  console.log('ℹ️  Purpose & Use Case:');
  console.log('  This creates an uncommitted wrangler.overrides.toml file for deployment overrides or custom routes.\n');

  const customDomain = (await askQuestion('Enter custom domain pattern (e.g. contact.splitphase.local): ')).trim();

  if (!customDomain) {
    console.log('No domain provided. Skipping.');
    return;
  }

  const localTomlContent = `# wrangler.overrides.toml (Git-ignored production deployment overrides)
# Generated by FormFlare Interactive Setup Wizard
name = "formflare"

[[routes]]
pattern = "${customDomain}"
custom_domain = true
`;

  const targetPath = path.join(__dirname, '..', 'wrangler.overrides.toml');
  fs.writeFileSync(targetPath, localTomlContent, 'utf-8');

  printManifest({
    modifiedFiles: [
      {
        path: targetPath,
        relativePath: 'wrangler.overrides.toml',
        status: 'CREATED / UPDATED',
        summary: `Custom Domain Route: ${customDomain}`,
      },
    ],
    nextSteps: [
      `Deploy with custom overrides: npx wrangler deploy -c wrangler.overrides.toml`,
      `Map 127.0.0.1 ${customDomain} in your local /etc/hosts file if testing locally.`,
    ],
  });
}

async function setupMultiSiteSecrets() {
  console.log('\n--- 🗝️  Multi-Tenant Per-Site Secrets & Webhooks Helper [OPTIONAL] ---');
  console.log('FormFlare supports site-specific Turnstile keys, Email routes, and Webhook URLs based on siteId.\n');

  const siteId = (await askQuestion('Enter target site identifier (siteId) [e.g. brainendeavor]: ')).trim();

  if (!siteId) {
    console.log('No site ID provided. Skipping.');
    return;
  }

  const cleanSiteId = siteId.replace(/[^a-zA-Z0-9]/g, '').toUpperCase();

  console.log(`\nCommands for site '${siteId}' (Prefix: ${cleanSiteId}):\n`);
  console.log(`  npx wrangler secret put TURNSTILE_SECRET_KEY_${cleanSiteId}`);
  console.log(`  npx wrangler secret put EMAIL_API_KEY_${cleanSiteId}`);
  console.log(`  npx wrangler secret put WEBHOOK_URL_${cleanSiteId}`);
  console.log('');

  printManifest({
    modifiedFiles: [],
    nextSteps: [
      `Run secret commands above for site: ${cleanSiteId}`,
    ],
  });
}

function printManifest({ modifiedFiles, nextSteps }) {
  console.log(`
========================================================================
📋 SETUP MANIFEST & MODIFIED RESOURCES SUMMARY
========================================================================`);

  if (modifiedFiles.length === 0) {
    console.log('  [NO FILES MODIFIED ON DISK]');
  } else {
    modifiedFiles.forEach((file) => {
      console.log(`  [FILE ${file.status}]  ${file.relativePath}`);
      console.log(`  Path:              ${file.path}`);
      console.log(`  Config Summary:    ${file.summary}`);
      console.log('  ----------------------------------------------------------------------');
    });
  }

  console.log('\n📌 NEXT STEPS:');
  nextSteps.forEach((step) => {
    console.log(`  • ${step}`);
  });
  console.log('========================================================================\n');
}

main().catch(console.error);
