#!/usr/bin/env node

/**
 * FormFlare Interactive Setup Wizard & Manifest Summary
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const askQuestion = (query) =>
  new Promise((resolve) => rl.question(query, resolve));

async function main() {
  console.log(`
┌─────────────────────────────────────────────────────────────┐
│ 🔥 FormFlare Interactive Setup Wizard                       │
└─────────────────────────────────────────────────────────────┘
`);

  console.log('Select setup target:');
  console.log('  1. Local Development (.dev.vars)');
  console.log('  2. Custom Local Domain Route (wrangler.local.toml)');
  console.log('  3. Cloudflare Production Secrets Helper\n');

  const choice = (await askQuestion('Enter choice (1-3) [default: 1]: ')).trim() || '1';

  if (choice === '1') {
    await setupLocalDev();
  } else if (choice === '2') {
    await setupLocalRoute();
  } else if (choice === '3') {
    await setupProdSecrets();
  } else {
    console.log('Invalid choice. Exiting.');
  }

  rl.close();
}

async function setupLocalDev() {
  console.log('\n--- Local Development Setup (.dev.vars) ---');
  const provider = (await askQuestion('Select Email Provider (console/none/resend/mailgun/sendgrid) [console]: ')).trim() || 'console';
  const emailTo = (await askQuestion('Enter notification target email (EMAIL_TO) [dev@example.com]: ')).trim() || 'dev@example.com';
  const emailFrom = (await askQuestion('Enter sender email (EMAIL_FROM) [noreply@localhost]: ')).trim() || 'noreply@localhost';
  const apiKey = (await askQuestion('Enter local API Key [dev-secret-key-123]: ')).trim() || 'dev-secret-key-123';

  const devVarsContent = `# FormFlare Local Development Environment (.dev.vars)
# Generated by FormFlare Interactive Setup Wizard
ENVIRONMENT=development
DEV_MODE=true
DEV_MOCK_TURNSTILE=true
ALLOWED_ORIGINS=*

TURNSTILE_SECRET_KEY=1x00000000000000000000AA00000000000
EMAIL_PROVIDER=${provider}
EMAIL_FROM=${emailFrom}
EMAIL_TO=${emailTo}
API_KEY=${apiKey}
`;

  const targetPath = path.join(__dirname, '..', '.dev.vars');
  fs.writeFileSync(targetPath, devVarsContent, 'utf-8');

  printManifest({
    modifiedFiles: [
      {
        path: targetPath,
        relativePath: '.dev.vars',
        status: 'CREATED / UPDATED',
        summary: `DEV_MODE=true, EMAIL_PROVIDER=${provider}, EMAIL_TO=${emailTo}, API_KEY=${apiKey}`,
      },
    ],
    nextSteps: [
      'Run local dev server: npx wrangler dev',
      'Submit a form locally to test console logger output.',
      'Check status: git status (verify .dev.vars remains untracked)',
    ],
  });
}

async function setupLocalRoute() {
  console.log('\n--- Custom Domain Route Setup (wrangler.local.toml) ---');
  const customDomain = (await askQuestion('Enter custom domain pattern (e.g. contact.splitphase.io): ')).trim();

  if (!customDomain) {
    console.log('No domain provided. Skipping.');
    return;
  }

  const localTomlContent = `# wrangler.local.toml (Git-ignored local override)
# Generated by FormFlare Interactive Setup Wizard
name = "formflare-local"

[[routes]]
pattern = "${customDomain}"
custom_domain = true
`;

  const targetPath = path.join(__dirname, '..', 'wrangler.local.toml');
  fs.writeFileSync(targetPath, localTomlContent, 'utf-8');

  printManifest({
    modifiedFiles: [
      {
        path: targetPath,
        relativePath: 'wrangler.local.toml',
        status: 'CREATED / UPDATED',
        summary: `Custom Domain Route: ${customDomain}`,
      },
    ],
    nextSteps: [
      `Deploy using local config: npx wrangler deploy -c wrangler.local.toml`,
      `Verify DNS binding in Cloudflare Dashboard`,
    ],
  });
}

async function setupProdSecrets() {
  console.log('\n--- Production Secrets Deployment Commands ---');
  console.log('Run the following CLI commands to configure Cloudflare Production Secrets safely:\n');

  console.log('  npx wrangler secret put TURNSTILE_SECRET_KEY');
  console.log('  npx wrangler secret put API_KEY');
  console.log('  npx wrangler secret put EMAIL_API_KEY');
  console.log('  npx wrangler secret put EMAIL_FROM');
  console.log('  npx wrangler secret put EMAIL_TO');

  printManifest({
    modifiedFiles: [],
    nextSteps: [
      'Execute the secret dispatches above in your terminal.',
      'Deploy clean worker: npx wrangler deploy',
    ],
  });
}

function printManifest({ modifiedFiles, nextSteps }) {
  console.log(`
========================================================================
📋 SETUP MANIFEST & MODIFIED RESOURCES SUMMARY
========================================================================`);

  if (modifiedFiles.length === 0) {
    console.log('  [NO FILES MODIFIED ON DISK]');
  } else {
    modifiedFiles.forEach((file) => {
      console.log(`  [FILE ${file.status}]  ${file.relativePath}`);
      console.log(`  Path:              ${file.path}`);
      console.log(`  Config Summary:    ${file.summary}`);
      console.log('  ----------------------------------------------------------------------');
    });
  }

  console.log('\n📌 NEXT STEPS:');
  nextSteps.forEach((step) => {
    console.log(`  • ${step}`);
  });
  console.log('========================================================================\n');
}

main().catch(console.error);
