#!/usr/bin/env node

/**
 * FormFlare Interactive Setup Wizard & Manifest Summary
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const askQuestion = (query) =>
  new Promise((resolve) => rl.question(query, resolve));

async function main() {
  console.log(`
┌─────────────────────────────────────────────────────────────┐
│ 🔥 FormFlare Interactive Setup Wizard                       │
└─────────────────────────────────────────────────────────────┘
`);

  console.log('Select Setup Mode:');
  console.log('  1. 🛠️  Local Development Setup      [RECOMMENDED FOR LOCAL DEV]');
  console.log('  2. 🚀 Production Deployment Setup     [REQUIRED FOR PROD DEPLOY]');
  console.log('  3. ⚙️  Advanced Developer Tools     [OPTIONAL]');
  console.log('');

  const choice = (await askQuestion('Enter choice (1-3) [default: 1]: ')).trim() || '1';

  if (choice === '1') {
    await setupLocalDev();
  } else if (choice === '2') {
    await setupProdDeployment();
  } else if (choice === '3') {
    await setupAdvancedMenu();
  } else {
    console.log('Invalid choice. Exiting.');
  }

  rl.close();
}

async function setupLocalDev() {
  console.log('\n--- 🛠️  Local Development Environment Setup (.dev.vars) ---');
  console.log('This sets up your git-ignored local environment file (.dev.vars) for offline development.\n');

  const provider = (await askQuestion('Select Email Provider (console/none/resend/mailgun/sendgrid) [console]: ')).trim() || 'console';
  const emailTo = (await askQuestion('Enter notification target email (EMAIL_TO) [dev@example.com]: ')).trim() || 'dev@example.com';
  const emailFrom = (await askQuestion('Enter sender email (EMAIL_FROM) [noreply@localhost]: ')).trim() || 'noreply@localhost';
  const apiKey = (await askQuestion('Enter local API Key [dev-secret-key-123]: ')).trim() || 'dev-secret-key-123';

  const devVarsContent = `# FormFlare Local Development Environment (.dev.vars)
# Generated by FormFlare Interactive Setup Wizard
ENVIRONMENT=development
DEV_MODE=true
DEV_MOCK_TURNSTILE=true
ALLOWED_ORIGINS=*

TURNSTILE_SECRET_KEY=1x00000000000000000000AA00000000000
EMAIL_PROVIDER=${provider}
EMAIL_FROM=${emailFrom}
EMAIL_TO=${emailTo}
API_KEY=${apiKey}
`;

  const targetPath = path.join(__dirname, '..', '.dev.vars');
  fs.writeFileSync(targetPath, devVarsContent, 'utf-8');

  printManifest({
    modifiedFiles: [
      {
        path: targetPath,
        relativePath: '.dev.vars',
        status: 'CREATED / UPDATED',
        summary: `DEV_MODE=true, EMAIL_PROVIDER=${provider}, EMAIL_TO=${emailTo}, API_KEY=${apiKey}`,
      },
    ],
    nextSteps: [
      'Run local dev server: npx wrangler dev',
      'Submit a form locally to test console logger output.',
      'Check status: git status (verify .dev.vars remains untracked)',
    ],
  });
}

async function setupProdDeployment() {
  console.log('\n--- 🚀 Production Deployment Setup ---');
  console.log('Configures production environment variables & generates secret provisioning commands.\n');

  const allowedOrigins = (await askQuestion('Enter allowed CORS origins (ALLOWED_ORIGINS) [e.g. https://brainendeavor.com,https://splitphase.io]: ')).trim() || '*';
  const emailTo = (await askQuestion('Enter production alert recipient (EMAIL_TO) [e.g. alerts@yourdomain.com]: ')).trim();
  const provider = (await askQuestion('Select Production Email Provider (resend/sendgrid/mailgun/none) [resend]: ')).trim() || 'resend';

  console.log('\n📌 Save local production overrides to git-ignored .dev.vars? (y/N): ');
  const saveLocal = (await askQuestion('')).trim().toLowerCase();

  if (saveLocal === 'y' || saveLocal === 'yes') {
    const devVarsPath = path.join(__dirname, '..', '.dev.vars');
    let existingContent = fs.existsSync(devVarsPath) ? fs.readFileSync(devVarsPath, 'utf-8') : '';

    const newVars = `
# Production Overrides (Saved via Setup Wizard)
ENVIRONMENT=production
ALLOWED_ORIGINS=${allowedOrigins}
EMAIL_PROVIDER=${provider}
${emailTo ? `EMAIL_TO=${emailTo}` : ''}
`;
    fs.writeFileSync(devVarsPath, existingContent + newVars, 'utf-8');
    console.log('✅ Appended production overrides to .dev.vars');
  }

  console.log('\n📌 Cloudflare KMS Production Secret Commands');
  console.log('Execute the following commands in your terminal to set production secrets in Cloudflare KMS:\n');
  console.log('  npx wrangler secret put TURNSTILE_SECRET_KEY');
  console.log('  npx wrangler secret put API_KEY');
  if (provider !== 'none') {
    console.log('  npx wrangler secret put EMAIL_API_KEY');
  }

  printManifest({
    modifiedFiles: [],
    nextSteps: [
      'Set Cloudflare KMS secrets above.',
      'Deploy to Cloudflare Workers: npx wrangler deploy',
    ],
  });
}

async function setupAdvancedMenu() {
  console.log('\n--- ⚙️  Advanced Developer Tools (Optional) ---');
  console.log('  1. Custom Local Domain Route (wrangler.local.toml)');
  console.log('     ℹ️  Optional: Useful for testing same-origin CORS, cookies, or custom domain routing locally.');
  console.log('  2. Multi-Tenant Per-Site Secrets & Webhooks Helper');
  console.log('     ℹ️  Optional: Generate secret commands for multi-site keys (e.g. TURNSTILE_SECRET_KEY_BRAINENDEAVOR).\n');

  const choice = (await askQuestion('Enter choice (1-2) [default: 1]: ')).trim() || '1';

  if (choice === '1') {
    await setupLocalRoute();
  } else if (choice === '2') {
    await setupMultiSiteSecrets();
  } else {
    console.log('Invalid choice.');
  }
}

async function setupLocalRoute() {
  console.log('\n--- 🌐 Custom Domain Route Setup (wrangler.local.toml) [OPTIONAL] ---');
  console.log('ℹ️  Purpose & Use Case:');
  console.log('  This creates an uncommitted wrangler.local.toml file for testing local domain routes.');
  console.log('  Use this if you are testing same-origin CORS headers, cookies, or custom local domains');
  console.log('  (e.g., contact.splitphase.local via /etc/hosts) before deploying to production.\n');

  const customDomain = (await askQuestion('Enter custom domain pattern (e.g. contact.splitphase.local): ')).trim();

  if (!customDomain) {
    console.log('No domain provided. Skipping.');
    return;
  }

  const localTomlContent = `# wrangler.local.toml (Git-ignored local override)
# Generated by FormFlare Interactive Setup Wizard
name = "formflare-local"

[[routes]]
pattern = "${customDomain}"
custom_domain = true
`;

  const targetPath = path.join(__dirname, '..', 'wrangler.local.toml');
  fs.writeFileSync(targetPath, localTomlContent, 'utf-8');

  printManifest({
    modifiedFiles: [
      {
        path: targetPath,
        relativePath: 'wrangler.local.toml',
        status: 'CREATED / UPDATED',
        summary: `Custom Domain Route: ${customDomain}`,
      },
    ],
    nextSteps: [
      `Run local dev with local config: npx wrangler dev -c wrangler.local.toml`,
      `Map 127.0.0.1 ${customDomain} in your local /etc/hosts file if testing locally.`,
    ],
  });
}

async function setupMultiSiteSecrets() {
  console.log('\n--- 🗝️  Multi-Tenant Per-Site Secrets & Webhooks Helper [OPTIONAL] ---');
  console.log('FormFlare supports site-specific Turnstile keys and Webhook URLs based on siteId.\n');

  const siteId = (await askQuestion('Enter target site identifier (siteId) [e.g. brainendeavor]: ')).trim();

  if (!siteId) {
    console.log('No site ID provided. Skipping.');
    return;
  }

  const cleanSiteId = siteId.replace(/[^a-zA-Z0-9]/g, '').toUpperCase();

  console.log(`\nCommands for site '${siteId}' (Prefix: ${cleanSiteId}):\n`);
  console.log(`  npx wrangler secret put TURNSTILE_SECRET_KEY_${cleanSiteId}`);
  console.log(`  npx wrangler secret put WEBHOOK_URL_${cleanSiteId}`);
  console.log('');

  printManifest({
    modifiedFiles: [],
    nextSteps: [
      `Run secret commands above for site: ${cleanSiteId}`,
    ],
  });
}

function printManifest({ modifiedFiles, nextSteps }) {
  console.log(`
========================================================================
📋 SETUP MANIFEST & MODIFIED RESOURCES SUMMARY
========================================================================`);

  if (modifiedFiles.length === 0) {
    console.log('  [NO FILES MODIFIED ON DISK]');
  } else {
    modifiedFiles.forEach((file) => {
      console.log(`  [FILE ${file.status}]  ${file.relativePath}`);
      console.log(`  Path:              ${file.path}`);
      console.log(`  Config Summary:    ${file.summary}`);
      console.log('  ----------------------------------------------------------------------');
    });
  }

  console.log('\n📌 NEXT STEPS:');
  nextSteps.forEach((step) => {
    console.log(`  • ${step}`);
  });
  console.log('========================================================================\n');
}

main().catch(console.error);
